# Generated by Django 6.1 on 2026-09-12 14:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('rank', models.CharField(help_text='e.g. 1st Winner, Finalist, 1st Place, Favorite Winner', max_length=100)),
                ('issuer', models.CharField(help_text='e.g. BKKBN Provinsi DKI Jakarta', max_length=255)),
                ('category', models.CharField(choices=[('advocacy', 'Advocacy & Youth Leadership'), ('pageant', 'Cultural & Tourism Pageant'), ('business', 'Business & Entrepreneurship'), ('public-health', 'Public Health & Campaign'), ('academic', 'Academic Excellence')], default='advocacy', max_length=30)),
                ('year', models.CharField(help_text='e.g. 2024, 2026', max_length=10)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
