# Generated by Django 6.1 on 2026-09-13 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_award'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='category',
            field=models.CharField(choices=[('organization', 'Organization'), ('ambassador', 'Ambassador'), ('committee', 'Committee'), ('internship', 'Internship'), ('volunteer', 'Volunteer'), ('research', 'Research')], default='organization', max_length=20),
        ),
    ]
